version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: secret_board
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'Asia/Tokyo'
    volumes:
      - ../secret-board-db:/var/lib/postgresql/data
